### ISSUE TITLE
Implement hierarchy cache 

### ISSUE THREAD

**Issue by Nyholm** [php-cache/redis-adapter#1]
We need to support hierarchy keys in this [Redis](http://redis.io/) adapter.

Use the [documentation](http://www.php-cache.com/en/latest/implementing-cache-pools/hierarchy/) and the [PR on the Predis adapter](https://github.com/php-cache/predis-adapter/pull/7) as reference.

**Comment by Nyholm** [comment]
Ping @headbangya, can you do this?

**Comment by Headbangya** [comment]
I'm still quite new to Redis, but I'll have a look at it.

**Comment by Headbangya** [comment]
Might take a while longer than expected, found out I need to reinstall El Capitan.

**Comment by Nyholm** [comment]
Wow. Are you sure? How about: 
Brew install redis && brew install php56-redis

**Comment by Headbangya** [comment]
Yeah. I had some problems installing Ruby when I just got the computer and did an ugly fix for it. Now I have to pay the price since stuff are starting to get corrupted but I will probably be back up and running in a few hours.

**Comment by Nyholm** [comment]
Closed by #2
